version: "3"
services:
    traefik:
        image: traefik:alpine
        labels:
            - traefik.enable=true
            - traefik.port=8080
            - traefik.frontend.rule=Host:traefik.tudominio.com
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${PWD}/traefik.toml:/etc/traefik/traefik.toml
            - ${PWD}/acme.json:/acme.json
        ports:
            - 80:80
            - 443:443
            #- 8080:8080

    mariadb:
        image: 'bitnami/mariadb:10.1'
        environment:
            - MARIADB_USER=bn_moodle
            - MARIADB_DATABASE=bitnami_moodle
            - ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - 'mariadb_data:/bitnami'
    
    moodle:
        image: 'bitnami/moodle:3'
        environment:
            - MARIADB_HOST=mariadb
            - MARIADB_PORT_NUMBER=3306
            - MOODLE_DATABASE_USER=bn_moodle
            - MOODLE_DATABASE_NAME=bitnami_moodle
            - ALLOW_EMPTY_PASSWORD=yes
        expose:
            - "80"
        labels:
            - traefik.enable=true
            - traefik.port=80
            - traefik.frontend.rule=Host:moodle.tudominio.com
        volumes:
            - 'moodle_data:/bitnami'
        depends_on:
            - mariadb
volumes:
    mariadb_data:
        driver: local
    moodle_data:
        driver: local